version: '3'
services:
  nginx:
    image: nginx:stable-alpine-slim
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./data/:/usr/share/nginx/html:ro 
    ports:
      - 80:80
